### ISSUE TITLE
Where to find generated live photos?

### ISSUE THREAD

**Issue by am1006** [RhetTbull/makelive#12]
Hi @RhetTbull,

Amazing work! It's a pleasure to read the code you wrote. I've been playing with this library and absolutely love the easiness of making live photos using it.

After I run the command (or through the API), my understanding is that it will link two assets (a image and a video). I wonder how I could generate a live photo that can be imported to the device's album. Or if it has already been generated, where to find these live photos?

Cheers

**Comment by am1006** [comment]
I've found something about `.pvt` package from another thread. Not sure if this is relevant but I think this is what I've been looking for.

https://github.com/RhetTbull/makelive/issues/11#issuecomment-2168510697

**Comment by RhetTbull** [comment]
Hi. I'm glad you find this useful. When you run makelive, it adds a `ContentIdentifier` tag to both the photo and video asset. If you then import those two assets together into Photos, they will be automatically combined into a Live Photo. The Live Photo is not actually a single asset -- it's the photo and video files which are associated by the `ContentIdentifier` tag. The `.pvt` pacakge appears to be another way to combine these two but as best as I can tell, all it does is simplify moving the assets around the file system. To create one, you simply create a directory with the same basename as the image with `.pvt` extension, for example, `IMG_1234.pvt` then copy the photo and video that have been processed by makelive into this package. You also need to add `metadata.plist` with contents:

```xmp
<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd"><plist version="1.0"><dict><key>PFVideoComplementMetadataVersionKey</key><string>1</string></dict></plist>
```

Double-clicking the `.pvt` package will import the asset into Photos. There does not appear to be any other benefit of packaging the Live photos in this manner.

**Comment by am1006** [comment]
Great! Thanks for this @RhetTbull 

I have a implementation that I can share, but I guess you may already have implemented it:

```python
import os
import shutil
import sys

xml_metadata = (
    '<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" '
    '"http://www.apple.com/DTDs/PropertyList-1.0.dtd"><plist version="1.0"><dict>'
    '<key>PFVideoComplementMetadataVersionKey</key><string>1</string></dict></plist>'
)

def copyfile(src, dest):
    shutil.copyfile(src, dest)

def main(photo_path, movie_path, package_name):
    if not os.path.isfile(photo_path) or not photo_path.endswith('.jpg'):
        print("Invalid JPG file.")
        return

    if not os.path.isfile(movie_path) or not movie_path.endswith('.mov'):
        print("Invalid MOV file.")
        return

    file_name = os.path.splitext(os.path.basename(photo_path))[0]

    if os.path.splitext(os.path.basename(movie_path))[0] != file_name:
        print("The JPG and MOV files do not have matching names.")
        return

    live_photo_dir = f'./{package_name}.pvt'
    # Create .pvt container
    os.makedirs(live_photo_dir, exist_ok=True)
    # Copy jpg & mov
    copyfile(movie_path, f'./{live_photo_dir}/{package_name}.mov')
    copyfile(photo_path, f'./{live_photo_dir}/{package_name}.jpg')
    # Create metadata file
    with open(f'./{live_photo_dir}/metadata.plist', 'w') as metadata_file:
        metadata_file.write(xml_metadata)

if __name__ == "__main__":
    if len(sys.argv) != 4:
        print("Usage: python script.py <photo.jpg> <movie.mov> <package_name>")
    else:
        photo_path = sys.argv[1]
        movie_path = sys.argv[2]
        package_name = sys.argv[3]
        main(photo_path, movie_path, package_name)
```

**Comment by RhetTbull** [comment]
@am1006 Thanks for the code contribution. I made a change to your `save_live_photo_pair_as_pvt()` to return both the asset ID and the path as a tuple. That made the rest of the code a little more consistent.

**Comment by am1006** [comment]
> @am1006 Thanks for the code contribution. I made a change to your `save_live_photo_pair_as_pvt()` to return both the asset ID and the path as a tuple. That made the rest of the code a little more consistent.

Thank you @RhetTbull! I was literally reading your code ~2 minutes ago 😄. Beautiful code!
