### ISSUE TITLE
iOS new metadata

### ISSUE THREAD

**Issue by am1006** [RhetTbull/makelive#20]
Hi @RhetTbull 

I've been exploring the metadata used by Live photos. It seems that iOS 17 may have introduced a new sets of metadata for live photos, which makes the live photos generated by this package not compatible with the Wall Paper feature. 

See the discussion here: https://forums.macrumors.com/threads/ios-17-live-photos-motion-not-available-lock-screen.2403161/

**Comment by RhetTbull** [comment]
I tried to follow that thread but it was quite long and not clear to me what the real issue is. I don't use live wallpaper and I don't have time to explore this issue. Happy to consider a PR if someone else wants to work on it.

**Comment by am1006** [comment]
> I tried to follow that thread but it was quite long and not clear to me what the real issue is. I don't use live wallpaper and I don't have time to explore this issue. Happy to consider a PR if someone else wants to work on it.

Yeah it was confusing.

I'm having a better understanding now - it is more or less an issue related to the video length (video must be < 1min). Don't think it's something specific to this repository's work.

I will close this issue now.
